<?php
/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Find the sum of the first 10000 triangle numbers.
*/
$t=[3];
$sum=1+3;
for($i=4,$j=1; $i<=10001; $i++,$j++){
	$t[$j]=$t[$j-1]+$i-1;
	$sum+=$t[$j];
}
echo($sum);
?>