<?php
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
$t=[1, 2];
$sum=0;
for($i=2; $i<32; $i++){
	$t[$i]=$t[$i-1]+$t[$i-2];
	if($t[$i]<4000000 && $t[$i]%2==0){
		$sum+=$t[$i];
	}
}
$sum=$sum+$t[1];
echo($sum);
?>